-- MySQL Script generated by MySQL Workbench
-- Tue Apr 24 14:52:12 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Portal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Portal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Portal` DEFAULT CHARACTER SET utf8 ;
USE `Portal` ;

-- -----------------------------------------------------
-- Table `Portal`.`tipo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portal`.`tipo_usuarios` (
  `idTipo` INT NOT NULL,
  `descricaoTipo` VARCHAR(255) NOT NULL,
  `ativo` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idTipo`),
  UNIQUE INDEX `descricaoTipo_UNIQUE` (`descricaoTipo` ASC));


-- -----------------------------------------------------
-- Table `Portal`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portal`.`Usuarios` (
  `IDusuario` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  `tipo` INT NULL,
  `CPF` INT NULL,
  `AlteraSenha` BINARY(1) NULL,
  `usuario` VARCHAR(45) NULL,
  `ativo` TINYINT NULL,
  PRIMARY KEY (`IDusuario`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  CONSTRAINT `tipoUsuario`
    FOREIGN KEY (`tipo`)
    REFERENCES `Portal`.`tipo_usuarios` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portal`.`Lojas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portal`.`Lojas` (
  `idLojas` INT NOT NULL,
  `CNPJ` INT NULL,
  `NomeLoja` VARCHAR(45) NULL,
  `Apelido_Loja` VARCHAR(45) NULL,
  PRIMARY KEY (`idLojas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portal`.`Cargo_Lojas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portal`.`Cargo_Lojas` (
  `idCargo` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portal`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portal`.`Vendedor` (
  `idVendedor` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `CPF` INT NULL,
  `idCargo` INT NULL,
  `idLojas` INT NULL,
  PRIMARY KEY (`idVendedor`),
  INDEX `loja_pertence_idx` (`idLojas` ASC),
  INDEX `cargo_idx` (`idCargo` ASC),
  CONSTRAINT `loja_pertence`
    FOREIGN KEY (`idLojas`)
    REFERENCES `Portal`.`Lojas` (`idLojas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cargo`
    FOREIGN KEY (`idCargo`)
    REFERENCES `Portal`.`Cargo_Lojas` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portal`.`VendasCabec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portal`.`VendasCabec` (
  `idVenda` INT NOT NULL,
  `numVenda` VARCHAR(55) NULL,
  `idVendedor` INT NULL,
  `ValorTotal` VARCHAR(45) NULL,
  `idLojas` INT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `vendedores_idx` (`idVendedor` ASC),
  INDEX `lojaPertence_idx` (`idLojas` ASC),
  CONSTRAINT `lojaPertence`
    FOREIGN KEY (`idLojas`)
    REFERENCES `Portal`.`Lojas` (`idLojas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `vendedores`
    FOREIGN KEY (`idVendedor`)
    REFERENCES `Portal`.`Vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portal`.`Metas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portal`.`Metas` (
  `idMetas` INT NOT NULL,
  `idLojas` INT NULL,
  `valorMeta` DECIMAL NULL,
  `periodo` DATETIME NULL,
  PRIMARY KEY (`idMetas`),
  INDEX `lojaPertence_idx` (`idLojas` ASC),
  CONSTRAINT `lojaPertence`
    FOREIGN KEY (`idLojas`)
    REFERENCES `Portal`.`Lojas` (`idLojas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portal`.`fatores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portal`.`fatores` (
  `idMetas` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `idLojas` INT NULL,
  `periodo` VARCHAR(45) NULL,
  `idCargo` INT NULL,
  PRIMARY KEY (`idMetas`),
  INDEX `cargo_idx` (`idCargo` ASC),
  INDEX `fk_lojas_idx` (`idLojas` ASC),
  CONSTRAINT `cargo`
    FOREIGN KEY (`idCargo`)
    REFERENCES `Portal`.`Cargo_Lojas` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lojas`
    FOREIGN KEY (`idLojas`)
    REFERENCES `Portal`.`Lojas` (`idLojas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Portal`.`param_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portal`.`param_usuarios` (
  `IDusuario` INT NOT NULL,
  `ativo` TINYINT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IDusuario`),
  CONSTRAINT `fk_usuarios`
    FOREIGN KEY (`IDusuario`)
    REFERENCES `Portal`.`Usuarios` (`IDusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
